#spring:
#  application:
#    name: CanteenManagement
#
#  datasource:
#    url: jdbc:sqlserver://HBCDVDB101.harambee.co.za:1433;databaseName=CantenManagment_db;instanceName=SQL;encrypt=true;trustServerCertificate=true
#    username: dbaccessuser
#    password: Secret123$
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
#      hibernate.format_sql: true
